### ISSUE TITLE
Add custom marker overlay dependent on marker type

### ISSUE THREAD

**Issue by tscholze** [tscholze/kotlin-surfaceduo-duobahn#13]
Till now, the app shows the default Map marker which provides not a lot of information.

That's why we need to add a custom map marker overlay which could take up to 50% if the screen that shows content dependent on the marker type.

Examples:

Webcam: Shows the webcam preview
Roadwork: Shows the location and the reason, e.g.

![Bildschirmfoto 2022-02-09 um 19 45 08](https://user-images.githubusercontent.com/5583469/153268750-5971b52f-6d16-4aea-a239-93e67b18809b.png)

**Comment by MarcelReiter** [comment]
In progress - i guess it'l take until the weekend, since i don't have to much time in the moment
